#!/bin/bash

LIBDIRS=chsdi/public/lib



for lib in openlayers geoext
do
    if [ -d ${LIBDIRS}/${lib}/.git ]
    then
        cd ${LIBDIRS}/${lib}
        git pull origin 
    else
        cd ${LIBDIRS}
        rm -rf ${lib}
        git clone https://github.com/${lib}/${lib}.git
    fi
    cd -
    if [ -O ${LIBDIRS}/${lib} ]
    then
        chmod -R g+rw ${LIBDIRS}/${lib}
    fi
done
